### PR TITLE
Fix #11

### LINKED ISSUE #11: Add settings menu
We need settings menu to avoid hardcoded image resolution, bind port, ect.

### PR DESCRIPTION
**Pull request by gsssrao**
Fix #11 
Instead of using Intent I can use preference editor and shorten the code. Also, during onResume(), I have not stopped the adapter of the ICE. So, the initial port is still open. Have a look at the code and tell me if anything needs to be changed or implemented differently.

### CODE REVIEW

**Comment by ojgarciab** [comment]
It's a normal behavior (possibly I will change it when update to the new Image interface that can drop an exception). For now requests are queued until camera is available again.

PS: could you confirm that you have enough privileges to merge yourself the pull request?

**Comment by gsssrao** [comment]
No, at present I don't have the permission to merge the pull request.

**Comment by ojgarciab** [comment]
Sorry, try again. I forgot to add repository to editors team.

**Comment by gsssrao** [comment]
Could you explain me the lock screen part, i.e do you want a lock screen for that specific app? 
I have also implemented the wake lock, will merge it soon.

**Pull request merged**
